---
# file: roles/raspberry/Tasks/main.yml

- import_tasks: install.yml
  tags: install

# Deprecated in favour of docker containers
# - import_tasks: nginx.yml
#   tags: nginx

- import_tasks: networking.yml
  tags: networking

- import_tasks: docker.yml
  tags: docker_install

- import_tasks: kubernetes.yml

- import_tasks: uv4l.yml

- import_tasks: vpn.yml


- import_tasks: other.yml

- import_tasks: gloveberry.yml
  tags:
    - gloveberry_install
    - gloveberry_setup
