---
# file: roles/raspberry/Tasks/other.yml

- name: Install networking requirements
  apt: pkg={{ item.name }} state=present update_cache=yes
  with_items:
    - { name: 'isc-dhcp-server'}
    - { name: 'hostapd'}
    - { name: 'bridge-utils'}
    - { name: 'wiringpi'}
    - { name: 'screen'}
    - { name: 'minicom'}
  tags: networking-install

- name: copy interface conf
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'etc/network/interfaces',         dest: '/etc/network/interfaces',         state: 'present'}
    - { src: 'etc/network/interfaces.d/eth0',  dest: '/etc/network/interfaces.d/eth0',  state: 'present'}
    - { src: 'etc/network/interfaces.d/br0',  dest: '/etc/network/interfaces.d/br0',  state: 'present'}
    - { src: 'etc/network/interfaces.d/wlan0', dest: '/etc/network/interfaces.d/wlan0', state: 'present'}
    - { src: 'etc/network/interfaces.d/wlan1', dest: '/etc/network/interfaces.d/wlan1', state: 'present'}
    # - { src: 'etc/wpa_supplicant/wpa_supplicant-wlan0.conf', dest: '/etc/wpa_supplicant/wpa_supplicant-wlan0.conf', state: 'present'}
    - { src: 'etc/wpa_supplicant/wpa_supplicant-wlan1.conf', dest: '/etc/wpa_supplicant/wpa_supplicant-wlan1.conf', state: 'present'}
  tags:
    - networking-config
    - interfaces

# - name: restart eth0 and bridge
#   shell: "ifdown eth0 && ifup eth0 && ifdown br0 && ifup br0"
#   tags:
#     - networking-eth-restart
#
- name: restart interface wlan0
  shell: "ifdown wlan0 && ifup wlan0"
  tags:
    - router
    - interface
#
# - name: restart interface wlan1
#   shell: "ifdown wlan1 && ifup wlan1"
#   tags:
#     - router
#     - interface
#
#- name: restart interface eth0
#  #service: name=networking state=restarted args=wlan1
#  shell: "ifdown eth0 && ifup eth0"
#  tags: router

- name: copy DHCP conf
  copy: src=etc/dhcp/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  tags: router

- name: copy isc-dhcp-server conf
  copy: src=etc/default/isc-dhcp-server dest=/etc/default/isc-dhcp-server
  tags: router
  notify: restart isc-dhcp-server

- name: Enabling ipv4 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.ip_forward='
    line: 'net.ipv4.ip_forward=1'

- name: set nat
  shell: "{{ item.name }}"
  with_items:
    - { name: 'sysctl -w net.ipv4.ip_forward=1' }
    - { name: 'sysctl -p /etc/sysctl.conf'} # this to apply "Enabling ipv4 forwarding"

    # This config when wlan0 is the public interface
    # - { name: 'iptables -A FORWARD -i wlan1 -o wlan0 -j ACCEPT' }
    # - { name: 'iptables -A FORWARD -i wlan0 -o wlan1 -m state --state RELATED,ESTABLISHED -j ACCEPT' }
    # - { name: 'iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE' }

    # This config when wlan1 is the public interface
    - { name: 'iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT' }
    - { name: 'iptables -A FORWARD -i wlan1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT' }
    - { name: 'iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE' }

    - { name: 'iptables-save' }
    - { name: 'iptables-save > /etc/firewall.conf' }
    - { name: 'echo "iptables-restore < /etc/iptables.ipv4.nat" > /lib/dhcpcd/dhcpcd-hooks/70-ipv4-nat' }
#
# iptables -A FORWARD -i wlan0 -o wlan1 -j ACCEPT
# iptables -A FORWARD -i wlan1 -o wlan0 -m state --state ESTABLISHED,RELATED -j ACCEPT
# iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
# iptables-save

  tags:
   - router
   - iptables
   - vpn-config
- name: Place hostapd conf file in hte daemon startup script
  copy:
    src: etc/supervisor/conf.d/hostapd.conf
    dest: /etc/supervisor/conf.d/hostapd.conf
  tags:
    - hostapd
  notify:
    - Restart supervisor

- name: copy hostapd conf
  copy: src=etc/hostapd/hostapd.conf dest=/etc/hostapd/hostapd.conf
  tags:
    - router
    - hostapd
  notify: Restart hostapd

# - name: start pptpd
#   service: name=pptpd state=restarted
#   tags:
#     - router
#     - vpn-config
#
# - name: download clusterhat
#   copy:
#     src: usr/local/bin/clusterhat
#     dest: /usr/local/bin/clusterhat
#     mode: 755
