---

- name: restart isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: restarted

- name: Restart hostapd
  systemd:
    state: restarted
    daemon_reload: yes
    name: hostapd

- name: Restart supervisor
  service:
    name: supervisor
    state: restarted
